<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\ProductController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\CategoryController;
use App\Http\Controllers\Api\OrderController;
use App\Http\Controllers\Api\PaymentController;
use App\Http\Controllers\Api\AdminOrderController;
use App\Http\Controllers\Api\AdminProductController;
use App\Http\Controllers\Api\AdminVoucherController;
use App\Http\Controllers\Api\AdminCategoryController;
use App\Http\Controllers\Api\AdminUserController;
use App\Http\Controllers\Api\VoucherController;
use App\Http\Controllers\Api\ReviewController;
use App\Http\Controllers\Api\ChatController;
use App\Http\Controllers\Api\ShippingController;
use App\Http\Controllers\Api\ImageSearchController;
Route::prefix('v1')->group(function () {
    Route::get('/ping', function () {
      return response()->json(['message' => 'API v1 OK']);
    });
    Route::middleware('throttle:20,1')->post('/chat', [ChatController::class, 'send']);
    Route::get('/categories', [CategoryController::class, 'index']);
    Route::get('/shipping/provinces', [ShippingController::class, 'provinces']);
    Route::get('/shipping/districts', [ShippingController::class, 'districts']);
    Route::get('/shipping/wards', [ShippingController::class, 'wards']);
    Route::post('/shipping/calculate-fee', [ShippingController::class, 'calculateFee']);
    Route::post('/search/by-image', [ImageSearchController::class, 'searchByImage']);
    Route::get('/products', [ProductController::class, 'index']);
    Route::get('/products/{id}', [ProductController::class, 'show']);
    Route::get('/products/{product}/reviews', [ReviewController::class, 'index']);
    Route::get('/vouchers', [VoucherController::class, 'index']);
    Route::middleware('throttle:5,1')->group(function () {
        Route::post('/register', [AuthController::class, 'register']);
        Route::post('/login', [AuthController::class, 'login']);
    });
    Route::middleware('auth:sanctum')->group(function () {
      Route::get('/user', [AuthController::class, 'user']);
      Route::put('/user/profile', [AuthController::class, 'updateProfile']);
      Route::put('/user/password', [AuthController::class, 'updatePassword']);
      Route::post('/logout', [AuthController::class, 'logout']);
      Route::get('/orders', [OrderController::class, 'index']);
      Route::post('/orders', [OrderController::class, 'store']);
      Route::get('/me/vouchers', [VoucherController::class, 'myVouchers']);
      Route::post('/vouchers/validate', [VoucherController::class, 'validateVoucher']);
      Route::post('/vouchers/{voucher}/save', [VoucherController::class, 'save']);
      Route::patch('/orders/{order}/cancel', [OrderController::class, 'cancel']);
      Route::get('/products/{product}/reviews/eligibility', [ReviewController::class, 'eligibility']);
      Route::post('/products/{product}/reviews', [ReviewController::class, 'store']);
      Route::post('/payment/intent', [PaymentController::class, 'createIntent']);
      Route::post('/payment/confirm', [PaymentController::class, 'confirmPaid']);
      Route::middleware('admin')->prefix('admin')->group(function () {
          Route::get('/orders', [AdminOrderController::class, 'index']);
          Route::patch('/orders/{order}/status', [AdminOrderController::class, 'updateStatus']);
          Route::get('/orders/{order}', [AdminOrderController::class, 'show']);
          Route::patch('/orders/{order}/cancel', [AdminOrderController::class, 'cancel']);
          Route::post('/orders/{order}/send-invoice', [AdminOrderController::class, 'sendInvoice']);
          Route::get('/stats/revenue-by-day', [AdminOrderController::class, 'revenueByDay']);
          Route::get('/products', [AdminProductController::class, 'index']);
          Route::get('/products/{product}', [AdminProductController::class, 'show']);
          Route::post('/products', [AdminProductController::class, 'store']);
          Route::put('/products/{product}', [AdminProductController::class, 'update']);
          Route::delete('/products/{product}', [AdminProductController::class, 'destroy']);
          Route::post('/products/upload-image', [AdminProductController::class, 'uploadImage']);
          Route::get('/vouchers', [AdminVoucherController::class, 'index']);
          Route::post('/vouchers', [AdminVoucherController::class, 'store']);
          Route::get('/vouchers/{voucher}', [AdminVoucherController::class, 'show']);
          Route::put('/vouchers/{voucher}', [AdminVoucherController::class, 'update']);
          Route::delete('/vouchers/{voucher}', [AdminVoucherController::class, 'destroy']);
          Route::patch('/vouchers/{voucher}/toggle', [AdminVoucherController::class, 'toggleActive']);
          Route::get('/users', [AdminUserController::class, 'index']);
          Route::get('/users/{user}', [AdminUserController::class, 'show']);
          Route::get('/categories', [AdminCategoryController::class, 'index']);
          Route::post('/categories', [AdminCategoryController::class, 'store']);
          Route::post('/categories/upload-image', [AdminCategoryController::class, 'uploadImage']);
          Route::put('/categories/{category}', [AdminCategoryController::class, 'update']);
          Route::delete('/categories/{category}', [AdminCategoryController::class, 'destroy']);
      });
    });
    Route::post('/payment/webhook', [PaymentController::class, 'webhook']);
});

